### ISSUE TITLE
Don't work with Flexible publish plugin

### ISSUE THREAD

**Issue by ghost** [jenkinsci/slack-plugin#41] opened 2015-01-17 12:52 UTC
When using with Flexible publish plugin it fails.

https://wiki.jenkins-ci.org/display/JENKINS/Flexible+Publish+Plugin

**Comment by samrocketman** [comment] 2015-01-30 06:48
In what way?  Any specific errors or logs you can post?  What is the expected behavior vs the behavior you witnessed?

**Comment by samrocketman** [comment] 2015-01-30 06:50
Also what's the use case for wanting to configure multiple slack publishers?  Do you have teams on more than one slack instance being notified?

**Comment by alexandre-zia-movile** [comment] 2015-01-30 12:00
There are no error or stack traces that I could find, the scenario is as follows:

We have a job in which we test for a determined condition, if that condition does not match, the job stops with no error, and if it stops we don't want to be notified in slack.
If the job continues, then we want to get notified in slack.

We are using "Flexible Publish" plugin to accomplish this, so at "Post Build Actions" we added a "flexible publish" item, setup a "conditional action" to determine if the job must stop or continue, and several "actions" to be executed if the job must continue.
The last of this "actions" is "Slack Notifications", 

If the conditional action decides to continue job execution all actions perform as expected but we get no notification in Slack. (no errors are shown, no stack traces)
If we remove "Slack notifications" item from inside this "Flexible plugin" item, and put "Slack notifications" as a separated and independent last step (as usual), then the notifications works, we got notified in slack, but in this case we are notified even if the conditional step in flexible plugin determines to stop the job, so this is a no go for us, as we get notified for every build.

Hope I was clear enough, let me know if you need more details.
Thanks

**Comment by samrocketman** [comment] 2015-01-31 19:55
Thanks for clarifying.  I think that's more than enough information to validate the need for this to work.

**Comment by samrocketman** [comment] 2015-02-04 07:27
I don't actively develop this plugin.  I will be maintaining pull requests and releases from now on.  Please feel free to contribute this feature!

**Comment by samrocketman** [comment] 2015-02-25 00:36
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by fredr** [comment] 2016-03-30 11:03
It seems it is not possible to have different configurations for the slack plugins in the same job. When the job configuration is saved, the values from the first instance of the plugin is copied to all instances of it.

I.e if I want to post to one channel if the job fails, and post to an other channel if the job succeeds, it is not possible to save the job with different values in "Project Channel".

**Comment by zekedroid** [comment] 2016-06-16 13:32
@fredr we're having the same issue as we were hoping to send job failures to our more active channel, and job successes (which happen way more often) to a "dump" channel. I take it there is no workaround for this yet?

**Comment by MattJustMatt** [comment] 2016-07-04 00:30
Would love to see this...

**Comment by fredr** [comment] 2016-07-05 14:47
@zekedroid my walkaround was a bash script that can update slack using curl and jq (via the slack incoming web hook plugin) from jenkins, and run that script with flexible publish.

**Comment by jammurp** [comment] 2016-11-19 00:04
@fredr Thanks for your suggestion, very helpful. I have a job that receives different variables from other upstream jobs, and depending what is passed in I want to post to different channels. It was frustrating because I wasn't seeing any errors, the log said it was invoking the slack plugin, but then nothing would get posted to the slack channel. One way I was going to work around it was to create different Jenkins Jobs that had their own configuration, but I like your curl solution better.

**Comment by otherdave** [comment] 2016-12-13 12:39
@fredr were you able to use the Slack Notifications in a flexible publish at all? I'm trying to set up a simple "If the failure was on 'master', then send a failure notification, otherwise don't slack anything". With that config, using the regex matcher in Conditional Run to check the branch, I never get a slack notification at all.

I couldn't tell from the history here if the issue was that it didn't work when you tried multiple Slack publishers, or if even a single publisher wasn't working.

**Comment by fredr** [comment] 2016-12-14 14:47
@otherdave I could trigger it from flexible publish, but I never tried to *only* trigger it from flexible. I did use it from outside of flexible as well.

But the problem was that it could not have multiple configurations for the slack plugin within the same job.

**Comment by andrewbonney** [comment] 2017-12-13 09:24
If anyone here is still interested in this issue I believe it should be fixed by https://github.com/jenkinsci/slack-plugin/pull/361. I'd welcome further tests and feedback.

**Comment by MichaelKueller** [comment] 2018-03-16 09:14
I'm also having this issue with the flexible publish plugin. I would be very happy if #361 would get merged

**Comment by ntulele** [comment] 2018-06-27 21:10
+1 for #361

**Comment by timja** [comment] 2018-11-28 11:55
361 is merged and will be released soon

**Closed by timja** 2018-11-28 11:55 UTC
Labels: contributions welcome
