### ISSUE TITLE
2.0.x Regression: one message emitted for each matrix conf + global job

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [jenkinsci/slack-plugin#198] opened 2016-03-21 15:35 UTC
Hi, before 2.0.x I received only one message telling the results of an executed job in a matrix job, and that's what I wanted in slack (when something fails, I check the details). Since 2.0.x version (I guess is connected to move the config to a post-build action), I'm getting spammed with one message per configuration in a matrix job plus one for the global job itself, which is quite annoying (for a simple job with built in 2 different environments, I get 3 messages). If including changes, then I get 6 messages in total, because I get one message with the changes for each configuration (which looks exactly the same) and one saying "No changes"  for the global job (I presume, the message just says "No Changes.").

Here is an example of before/after (ok, before having the changes listed was pointless as it always shown "No changes"):

![before](https://cloud.githubusercontent.com/assets/2684688/13923869/8567efe2-ef82-11e5-803e-239d226aa039.png)

![now](https://cloud.githubusercontent.com/assets/2684688/13923964/d6cc93ec-ef82-11e5-8a60-f4de5820176a.png)

**Comment by rreinurm** [comment] 2016-04-05 19:31
I experienced the same issue and had to revert the plugin upgrade.

**Comment by kmadel** [comment] 2016-04-09 14:19
@rreinurm and @leandro-lucarella-sociomantic I don't use the Matrix Job type, so curious of your thoughts regarding if you think this is a fix or not: https://github.com/jenkinsci/hipchat-plugin/pull/50

**Comment by rreinurm** [comment] 2016-04-09 17:35
@kmadel I looked into Hipchat plugin and for Matrix Job type they have additional config option: 
<img width="444" alt="screen shot 2016-04-09 at 20 28 52" src="https://cloud.githubusercontent.com/assets/4215660/14405198/f76afe4a-fe91-11e5-8c8c-224752e2a5c8.png">
In my opinion this pattern makes total sense and would help us to reduce spamming if it's not needed.

**Comment by leandro-lucarella-sociomantic** [comment] 2016-04-11 11:20
Ditto. If no options are provided, I think only notifying about the parent makes the more sense (this is how the GitHub plugin works to set commit status for example).

**Comment by leandro-lucarella-sociomantic** [comment] 2016-04-11 11:21
And, @kmadel, thanks for following up on this!

**Comment by timja** [comment] 2018-11-28 15:19
closing in favour of PR

**Comment by MikaelSmith** [comment] 2018-12-11 20:49
Looks like the fix was reverted, can we reopen this issue?

**Comment by mattdodge** [comment] 2018-12-11 23:50
Although the originally PR was reverted, it does seem like this behavior has been fixed. I have confirmed that the behavior exists in 2.3 but since 2.4 and running from source it doesn't seem to be a problem anymore. There is quite a long history between 2.3 and 2.4 so it's possible this was fixed inadvertently?

Interestingly, the reason that #341 was reverted was because it added a dependency (matrix-plugin) that probably didn't need to be there. It looks like that dependency was added back as part of #406, I'm not totally sure why though. There are quite a few changes in that PR though, I suspect one of them is what fixed this issue.

So, good news:
 - This issue seems fixed

Bad/weird news:
 - How/when was it fixed?
 - Does this plugin need to depend on matrix-plugin?

**Comment by sbeaulie** [comment] 2018-12-12 22:33
@mattdodge for the record I have 2.4 and it is sending notifications for all cell combinations

**Comment by mattdodge** [comment] 2018-12-12 22:39
@sbeaulie Hmm that's interesting. I can't reproduce it for versions 2.4 and above. Confirming, you are seeing a Slack notification for both the matrix axis values as well as the parent job, yes? So if you had a matrix combination job called "My Job" with matrix axis "version" with versions "A" and "B" you would see 3 different notifications.
> My Job
> My Job >> A
> My Job >> B

I've confirmed this both on my local and also our production Jenkins which was previously seeing the problem.

Versions I am running:
```
Jenkins: 2.138
Slack Notification Plugin: 2.6
Matrix Configuration Parameter Plugin: 1.3.0
Matrix Project Plugin: 1.13
Matrix Reloaded Plugin: 1.1.3
```

Thanks for the heads up on the test dependency too @timja, I totally missed that.

**Comment by sbeaulie** [comment] 2018-12-13 00:11
@mattdodge I've edited my previous comment but I think maybe we posted at the same time. I only see it for the children (matrix combinations)

**Comment by mattdodge** [comment] 2018-12-13 21:53
Ah yes, I think I've been misunderstanding what the regression was here all along. I have been (incorrectly it seems) assuming this plugin used to send notifications for all matrix combinations but *not* the parent job. This is actually the behavior that I would desire (as opposed to only the parent job, not the combinations) but I can totally see reasons one would want the opposite.

With versions 2.0 to 2.3 the plugin sends for all, which it seems nobody really wants. 2.4+ sends only combination jobs, not the parent job. I'm ok with that as a user but that's just one vote. 

At this point I'd say it's up to the actual maintainers of this plugin (I am a mere user who is willing to help out) to decide what the desired behavior should be and whether the issue should be closed or not.

**Comment by sbeaulie** [comment] 2018-12-14 18:10
Since [hipchat is going EOL (slack bought it and is retiring it)](https://www.cnet.com/news/slack-is-buying-rival-hipchat-only-to-kill-it-off/) we are trying to get parity between the hipchat plugin and the slack plugin. This is for us the number one feature it does not have.

We asked this issue to be re-opened because the [original comments pointed](https://github.com/jenkinsci/slack-plugin/issues/198#issuecomment-207820459) to [that too](https://github.com/jenkinsci/slack-plugin/issues/198#issuecomment-208292816). I think the best approach is to give the user the option, with the default to what it is now?

I don't have a strong opinion on how this should be implemented, and am happy to help bring this back, but I thought if the work was already done before not to reinvent the wheel. And get the discussion started here.

**Comment by timja** [comment] 2018-12-15 10:30
should be able to use the reverted PR but do it without adding the dependency if possible

**Comment by timja** [comment] 2019-01-13 15:36
It's not an absolute must, but ideally a plugin should minimise its mandatory dependencies as much as possible, the question is should a notification plugin pull in another job type plugin.
Is it expected behaviour, and is there a simpler approach

If there's not a simpler approach then it's fine

**Closed** 2019-04-09 06:41 UTC
Labels: bug, contributions welcome, feedback needed

**Comment by Zitrax** [comment] 2021-03-24 11:31
I know this is a closed issue, but I couldn't figure out how or if this can be configured in a pipeline?
