### ISSUE TITLE
"Show Commit List with Titles and Authors" sometimes doesn't work

### ISSUE THREAD

**Issue by joshrabinowitz** [jenkinsci/slack-plugin#173] opened 2016-01-15 21:14 UTC
In our experience with the "Slack Notification Plugin" v 1.8.1, sometimes  "Show Commit List with Titles and Authors" doesn't have any effect. We're not sure what causes this to happen

Known bug? Workaround? Anything we can do (short of debugging and providing a fix) to help fix?

Thank you in advance for any assistance.

**Comment by tingzhang** [comment] 2016-02-02 08:28
i'm facing the same issue, any suggestion here?

**Comment by samrocketman** [comment] 2016-03-17 04:12
If you could investigate more conditions around how it occurs; that would be great.  I don't use the Slack plugin at all so it would be a large time investment to reproduce without some kind of understanding what is going on in the root cause.

Feel free to make use of my [bootstrapping environment](https://github.com/samrocketman/jenkins-bootstrap-slack) (bash required).

**Comment by timja** [comment] 2018-11-28 15:12
no feedback in 2 years closing

**Closed by timja** 2018-11-28 15:12 UTC
Labels: feedback needed
