### ISSUE TITLE
2.0.1 Release

### ISSUE THREAD

**Issue by kmadel** [jenkinsci/slack-plugin#193] opened 2016-03-17 10:03 UTC
Critical bug-fix release for #191  via #190 

TODO:
- [x] Create a new issue to track the release and give it the label `maintainer communication`.
- [x] Create a release branch. `git checkout origin/master -b prepare_release`
- [x] Update the release notes in `CHANGELOG.md`.
- [x] Open a pull request from `prepare_release` branch to `master` branch.  Merge it.
- [x] Fetch updated `master`.
- [x] Execute the release plugin.

Wait ~8 hours....
- [ ] Wait for the plugin to be released into the Jenkins Update Center.
- [ ] Successfully perform an upgrade from the last stable plugin release to the current release.

**Comment by OwensCode** [comment] 2016-03-17 13:11
I'm not sure where #188 is being tracked any more, so I'm not sure where to post this comment. Maybe it needs to be reopened. Anyway, I thing the `SlackNotifier$SlackJobProperty is missing its descriptor` is misleading and is not the real problem. I suspect that the actual problem is that the configs were not migrated from the 1.8 format to the 2.0 format for some reason. Then when the job runs Jenkins finds the 1.8 job properties and complains because they are no longer part of the form etc. I can replicate this by forcing the migration to be skipped. I think we need some logs to get a better idea of what's going on; anything after "Starting Settings Migration Process".

**Comment by kmadel** [comment] 2016-03-17 14:33
I believe that @samrocketman moved #188 into #191 
Regardless, I do believe that #188 was not quite as critical as #190 and wanted to get 2.0.1 out quickly for 2.0.1

**Comment by OwensCode** [comment] 2016-03-17 15:24
Thanks @kmadel. I saw that, but #191 was also closed.

**Comment by samrocketman** [comment] 2016-03-17 16:33
Perhaps closing #188 was premature on my part?  It can be re-opened.  I remember someone where I work describing the issue.  I'll ask them for more details.

**Comment by samrocketman** [comment] 2016-03-17 16:35
Was anyone else able to reproduce #190 using my method in #191?

**Comment by OwensCode** [comment] 2016-03-17 16:53
I have not had a chance to try reproducing #190.

I think #188 is caused by uploading a job config via the REST API. One of the people reporting it maintains their configs externally and uploads them via a Gradle plugin. In that scenario, the config is not migrated from 1.8 to 2.0 and you get that error, which is actually misleading. Restarting Jenkins fixed the issue for him because the configs were then migrated. I kind of feel like this is an issue that users will have to fix themselves ... if we somehow automatically migrate those configs, then they'll just keep maintaining the old format externally, and we'll be stuck with the config migration always having to take place. Maybe we can log an error when uploading an old format config or something.

@samrocketman I'd be interested to hear whether this is the same use case that your coworker is experiencing, or whether there are some cases where configs are somehow not being migrated.

**Comment by shaneargo** [comment] 2016-03-18 00:59
FYI, I was still having issues after installing 2.0.1. I was no longer getting the NullPointerException all over the place, but I started getting the `SlackNotifier$SlackJobProperty is missing its descriptor` when attempting to save the configuration.

I fixed the issue by uninstalling the plugin, deleting the `/var/lib/jenkins/plugins/slack*` files, restarting jenkins, installing 2.0.1 again and then configuring it again.

**Comment by samrocketman** [comment] 2016-03-18 01:37
I've re-opened #188 which describes a similar stack trace.

**Comment by OwensCode** [comment] 2016-03-18 13:13
@shaneargo, do you have a backup of a config.xml from the job that you could not save? If you do, can you post it here or in #188 please. The job configs were supposed to be automatically migrated from the 1.8 format, but it's possible that it failed to do that, resulting in those errors. If you don't have a backup of the config, could you look for "Starting Settings Migration Process" in your log files and post any errors that follow it.

**Comment by punitag** [comment] 2016-03-21 06:08
@shaneargo : I just tried your workaround of ``` uninstalling the plugin, deleting the /var/lib/jenkins/plugins/slack* files, restarting jenkins, installing 2.0.1 again and then configuring it again``` but even after that, I was getting a  ```SlackNotifier$SlackJobProperty is missing its descriptor``` when I installed 2.0.1.

**Comment by OwensCode** [comment] 2016-03-21 14:37
Moving any discussion about the `SlackNotifier$SlackJobProperty is missing its descriptor` error to #188.

**Closed** 2018-11-28 15:16 UTC
Labels: maintainer communication
