### ISSUE TITLE
Custom text on notification

### ISSUE THREAD

**Issue by danielgomezrico** [jenkinsci/slack-plugin#217] opened 2016-04-29 16:44 UTC
Will be cool to let it read the notification text from a file or std in or something so you can post something like:

```
released V 1.2.3
````

So every slack notify the released version of the code or other things.

**Comment by ElijahLynn** [comment] 2016-05-20 12:55
I think this is a duplicate of https://github.com/jenkinsci/slack-plugin/issues/163

**Closed** 2016-05-22 19:35 UTC
Labels: duplicate
