### ISSUE TITLE
Getting 2 messages on deploy start

### ISSUE THREAD

**Issue by EliFinkelshteyn** [jenkinsci/slack-plugin#161] opened 2015-11-25 20:46 UTC
I've been trying to get Jenkins to send me a "deploy is starting" message, but instead I get two:

<img width="458" alt="screenshot 2015-11-25 12 42 38" src="https://cloud.githubusercontent.com/assets/991121/11409036/24b4213c-9372-11e5-98c4-30b3578e1f11.png">

The extra message just clutters up Slack and doesn't tell me anything useful. I don't see any option to turn it off in configuration:

<img width="305" alt="screenshot 2015-11-25 12 45 01" src="https://cloud.githubusercontent.com/assets/991121/11409090/75504d00-9372-11e5-822b-b9d5b845e63c.png">

Am I missing something? Is there any way to disable this extra message?

**Comment by dpires** [comment] 2015-11-26 01:22
tl;dr No, there is no config to stop double messages for "Notify Build Start" as far as I can see.

Looking at ActiveNotifier, when a build starts, it sends 2 notifications,  the first is  the Cause of the build "Started by" and then it looks for changes, if found sends a second message "Started by changes by <user> ..."  If no changes are found, it sends a generic "Starting..."

I only 1 call is necessary, and in the lookup for changes, instead of returning null, replace it with the build Cause, "Started by user <user>"

**Comment by samrocketman** [comment] 2015-11-26 04:59
Already fixed in master.  See #137.

**Closed** 2016-03-15 01:28 UTC
Labels: possibly fixed next release
