### ISSUE TITLE
Support for Direct Messages

### ISSUE THREAD

**Issue by jamescarr** [jenkinsci/slack-plugin#110] opened 2015-06-23 05:03 UTC
It'd be cool to direct message users on commits if a slack user can be found for their email.

**Comment by samrocketman** [comment] 2015-06-23 11:51
Have you tried?  If it doesn't work then it is a feature that will have to be contributed.  I only maintain pull requests and releases.  You're welcome to contribute this feature!

**Comment by jamescarr** [comment] 2015-06-23 13:45
Heh I pretty much put the issue here to remind myself to try and hack on it
when I get time.

**Comment by jjudd** [comment] 2015-09-03 19:00
Found that @mentions and direct messaging are both possible, provided you know the user's slack username. This doesn't help much if you only know their email, however.

Custom message (for @mentions): <@username>
Channel (for direct message): @username1,@username2,...,@usernameN

**Comment by nevermindr** [comment] 2015-11-19 22:36
Looks like the only method to do this is
https://api.slack.com/methods/users.list/test

To use WebAPI we need to configure one more OAuth token - it does not work with the one you get when configuring jenkins integration.

It's also not clear where to get the email address from. Preconfigured value, user who has started the build, from commit information?

**Comment by samrocketman** [comment] 2015-11-19 22:53
I could see the [users.list method](https://api.slack.com/methods/users.list) having performance issues if a slack instance has thousands of users.  It's unfortunate there's not a `getUserByEmail` method which could be queried based on the committer and author emails in the commit.

Another interesting thought, using `git blame` to gather a list of individuals who should be notified about a build.  I [stumbled on a project](https://github.com/facebook/mention-bot) that does that today.

**Comment by samrocketman** [comment] 2015-11-26 05:19
Duplicate of earlier issue #39.

**Closed** 2015-11-26 05:19 UTC
Labels: duplicate
