### ISSUE TITLE
not pinging into slack?

### ISSUE THREAD

**Issue by holzfelix** [jenkinsci/slack-plugin#91] opened 2015-05-16 07:25 UTC
Hi I've installed the plugin in jenkins and set up slack 

then I've added credentials to project seetings and added a post build task

but it dosn't ping into slack 

why?

**Comment by samrocketman** [comment] 2015-05-16 23:56
Did you also check the boxes at the top?  You need to configure the job in two places.

1. At the top of the job configuration where you must check what notifications it should send.
1. Post-build actions at the bottom of the job configuration.

Did you do both of those?

**Comment by holzfelix** [comment] 2015-05-17 05:34
Yes both of this are done.

**Comment by samrocketman** [comment] 2015-05-17 06:32
You'll need to provide more info (stack traces maybe or something else that can help get to the root cause).  I can't replicate this behavior.  What version of Jenkins?  What version of the plugin?

**Comment by holzfelix** [comment] 2015-05-17 06:34
I'm using Jenkins 1.596.2
and slack plugin org.jenkins-ci.plugins:slack:1.7

**Comment by samrocketman** [comment] 2015-05-17 06:38
I'll test this tomorrow against the LTS version and see if I can replicate the behavior.

**Comment by holzfelix** [comment] 2015-05-17 06:39
that would be nice thank you

**Comment by samrocketman** [comment] 2015-05-18 00:01
I could not reproduce the error.  Steps taken.

```bash
mkdir jenkins-lts
wget http://mirrors.jenkins-ci.org/war-stable/latest/jenkins.war
mkdir home
JENKINS_HOME=home/ java -jar jenkins.war

#in a new terminal update the plugins
wget http://localhost:8080/jnlpJars/jenkins-cli.jar
jenkins="java -jar ./jenkins-cli.jar -s http://localhost:8080/"
UPDATE_LIST="$( $jenkins list-plugins | grep -e ')$' | awk '{ print $1 }' )"
if [ ! -z "${UPDATE_LIST}" ]; then
  $jenkins install-plugin ${UPDATE_LIST}
fi

#restart the jenkins instance
$jenkins install-plugin slack
#restart the jenkins instance again
```

Now I have a fresh copy of Jenkins LTS 1.596.2 and slack plugin 1.8 (released today).

1. I configured the slack plugin in the global settings.  The test connection button says success and a message was posted to slack during the test.
2. I created a sample job called `test`.  I gave it the build script `echo "Hello"`.
3. I checked all of the boxes in the slack plugin configuration for notifications just for the heck of it.
4. I added `Slack Notifications` to the Post-build Actions of the test job.
5. I clicked build.

Messages from the build showed up in slack.  I think you have something configured incorrectly or something was fixed in the latest plugin 1.8.  Try upgrading to slack plugin 1.8 and try again.

**Comment by holzfelix** [comment] 2015-05-18 05:56
Okay thats the difference ... when I click the test button it says also success but no message was postet. in the global settings what have you set up as token? token of the slack channel or of slack team?

**Comment by holzfelix** [comment] 2015-05-18 06:04
okay now I've updatet to slack 1.8 ... but now it always says failure while test connection

**Comment by samrocketman** [comment] 2015-05-18 06:48
That means you don't have it correctly configured.  Please double check your settings.  Ensure you have the right instance.  Ensure your token is correct for connecting to slack.  When it succeeds it will actually say success.  In the past it was just a false positive and wasn't a very good test.  With the most recent update the test connection button actually works.

**Comment by samrocketman** [comment] 2015-05-18 06:51
Take for example the Jenkins slack test instance.

* Instance: `jenkins-slack-plugin`
* The token: `A6sHDtxmw5eWp38SPanK06uL` (I changed it)  though you only need to sign up to see the latest token for testing purposes.  Get the token from the integrations section.
* Post to channel: `#slack-plugin-testing`

You need to have all of those settings correct.  Once you do, the slack posting should work.

**Comment by holzfelix** [comment] 2015-05-18 07:46
Don't have the field Instance ... I've only have Team-Domain / Integration Token / channel / build server url

wich token do I need? the one of the channel??

**Comment by samrocketman** [comment] 2015-05-18 07:53
Team-Domain is what I'm referring when I say slack instance.  You need to get the integration token from your team-domain/slack instance.  The jenkins integration in slack has instructions.

**Comment by samrocketman** [comment] 2015-05-19 02:30
Hello @holzfelix, did you figure out your settings and get the plugin configured?

**Comment by holzfelix** [comment] 2015-05-19 04:34
No dosn't work. I've set up general settings noting worked. I've set up the settings in build job which override the general settings. -> failure

**Comment by samrocketman** [comment] 2015-05-19 12:45
Is there any stack traces that are produced?

**Comment by samrocketman** [comment] 2015-05-31 00:25
This can't be reproduced by me after several attempts in many configurations.  I'm going to close this as invalid and believe @holzfelix is doing something wrong in his configuration.

**Closed** 2015-05-31 00:25 UTC
Labels: invalid

**Comment by graeson** [comment] 2015-11-12 20:33
Having similar problem ... Installed slack using jenkins-cli.jar and configured the plugin exactly as described on the slack integrations page (correct domain, token, and channel). Unfortunately, firing a "Test Connection" always returns "Failure". I tried restarting Jenkins, re-installing the plugin, and regenerating a new Slack token, but was not able to get passed the above mentioned "Failure". Running jenkins 1.638 and slack plugin 1.8.

**Comment by samrocketman** [comment] 2015-11-12 21:58
@graeson please open a new issue.  If you want feel free to refer to this issue with `#91` in the message body.
