### ISSUE TITLE
Credentials changed from system to global

### ISSUE THREAD

**Issue by webratz** [jenkinsci/slack-plugin#546] opened 2019-03-28 15:24 UTC
Hey, related #545:

the change discussed there implies that all the credentials used for the Slack plugin have to changed from a System scope to global scope.
In our use case we intentionally set those credentials to a System scope, so these are not accessible by the jobs, but the users are still able to send slack messages.
These helps us to restrict access top the actual token to admins, and therefore to be only used in the context of this plugin.

With the recent change we now would have to make the credentials available to  anyone that can run a Job. The creds could be read and used anywhere else for other use  which they are not intended for. So in my opinion we are now in a state with less security than before.

Do you see a way how the old behavior of being able to use System credentials could be there alongside the new options?

**Comment by timja** [comment] 2019-03-28 15:26
Sorry I don't quite understand your usecase.
You want jobs to not have access to the credential
But users still able to send messages? - How should that work if the job doesn't have access to it?

**Comment by webratz** [comment] 2019-03-28 15:35
The plugin and the actual pipeline is executed on the master, the build stages run on separate agents.
So its possible for the plugin to access the system credential, buts impossible for the user to read the credential during the job run.
This works quite good for us

**Comment by timja** [comment] 2019-03-28 15:38
It's not supposed to work like that though.

The slack plugin was misusing the credentials api previously

AFAIK the correct way to segregate secrets in that method is folder level credentials or some other scope, but it needs to be available to the job (Item)

**Comment by webratz** [comment] 2019-03-28 15:44
not sure about the exact code in jenkins core, but citing from the docs at https://jenkins.io/doc/book/using/using-credentials/
> System - if the credential/s to be added is/are for the Jenkins instance itself to interact with system administration functions, such as email authentication, agent connection, etc. Choosing this option applies the scope of the credential/s to a single object only.

In my understanding authentication to slack would be equivalent from the scope to email auth mentioned there. So this sounds to me like the ideal thing for a system credential

**Comment by timja** [comment] 2019-03-28 15:49
Kind of

It's about who is acting on it

In this case we have an "Item" which is basically a "Job"

We're given an Item, and provide that to the credentials API as the context for the lookup to be performed

An Item is not allowed to lookup a system credential

They are more reserved for system functions like cloud credentials for agents etc.

Some more info here:
https://github.com/jenkinsci/credentials-plugin/blob/master/docs/consumer.adoc

**Comment by webratz** [comment] 2019-03-29 08:31
I totally agree that this view makes sense if the credential is stored eg by the team that creates a job in their subfolder. So for a per Job or per folder configuration of the plugin this the better choice for sure.

For the global configuration of the plugin (which we use) i'd still argue that using the SYSTEM scoped credential is valid and intended. I sadly cant link by line to the doc you shared, so i'll quote:

> We are doing this operation outside of the context of a single job, rather this is being performed on behalf of the entire Jenkins instance. Thus we should be performing this as ACL.SYSTEM and in the context of Jenkins.getInstance(). This has the additional benefit that the admin can restrict the high permission hook management credentials to CredentialsScope.SYSTEM which will prevent access by jobs.

So I'd say for the global setting, and only for this, the usage of a system credential benefits security and should be an usable way.

Side note: i appreciate the effort you put into maintaining this plugin and the prompt responses.

**Comment by timja** [comment] 2019-03-29 09:14
I get what you're trying to do, but the notification is happening in scope of the job

I'm going to close this as working as intended,

**Closed by timja** 2019-03-29 09:14 UTC
