### ISSUE TITLE
NullPointerException in ActiveNotifier.completed()

### ISSUE THREAD

**Issue by NfNitLoop** [jenkinsci/slack-plugin#535] opened 2019-03-05 00:03 UTC
Plugin version: 2.18.

~~~
[Slack Notifications] will send OnUnstableNotification because build matches and user preferences allow it
ERROR: Build step failed with exception
java.lang.NullPointerException
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:139)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:445)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1857)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Slack Notifications' marked build as failure
~~~

The line that fails is [here]:

[here]: https://github.com/jenkinsci/slack-plugin/blob/slack-2.18/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L139

~~~java
if (notifier.getCommitInfoChoice().showAnything()) { 
~~~

`notifier` isn't null, it's used in the previous line, so it looks like its `.commitInfoChoice` is null. And picking through the source code, I see that it gets initialized to null in some cases.

In particular, we're configuring Slack notifications via the Jenkins DSL, with some code that looks like this:

~~~groovy
if (notificationRoom) {
    slackNotifier {
        room(notificationRoom)
        startNotification(startNotification)
        notifySuccess(notifySuccess)
        notifyAborted(notifyAborted)
        notifyNotBuilt(notifyNotBuilt)
        notifyUnstable(notifyUnstable)
        notifyFailure(notifyFailure)
        notifyBackToNormal(notifyBackToNormal)
    }
}
~~~

I think that `slackNotifier` somehow relates to the `@Extension @Symbol("slackNotifier")` [here][2]

[2]: https://github.com/jenkinsci/slack-plugin/blob/slack-2.18/src/main/java/jenkins/plugins/slack/SlackNotifier.java#L471

But I have to admit, I'm not familiar with the inner workings of Jenkins plugins, so I'm not entirely sure how that `DescriptorImpl` ties back to the `SlackNotifier` parent class. But, it seems like, since we never explicitly pass in a `commitInfoChoice`, it's remaining `null`, which later raises an NPE.

## Potential fix ##

Maybe should update the SlackNotifier to default to `CommitInfoChoice.NONE`.  Probably a good idea to update `CommitInfoChoice.forDisplayName()` to return `NONE` for the base case too, instead of null, to avoid causing other such NPEs.

## Workaround? ##

In the meantime, if someone reading this knows of a workaround, we'd love to be able to work around the issue until there's a fix. But I'm not sure how to create a `CommitInfoChoice` from Jenkins DSL or pass it to the `slackNotifier{ ... }` code block.

**Comment by NfNitLoop** [comment] 2019-03-05 00:38
## Workaround ##

Aha, I found a code example at:
https://github.com/jenkinsci/job-dsl-plugin/wiki/Migration#slack

Looks like we can add `commitInfoChoice('NONE')`. 

Is there somewhere that documents that other than the Migration page?

Either way, it's still probably a good idea to have a sane default value there. 😄

**Comment by timja** [comment] 2019-03-05 07:24
While a default could be set, I've avoided doing that as I've marked this as a mandatory field, and jobdsl should be picking up that there's a databoundconstructor and requiring all fields to be set.

I don't use job dsl for this but I'll take a PR to add an example to the README.
Or to set the default (😢)...

**Comment by timja** [comment] 2019-08-19 20:32
Closing this, working as intended.

**Closed by timja** 2019-08-19 20:32 UTC
