### ISSUE TITLE
selecting "Notify Repeated Failure" is ignored

### ISSUE THREAD

**Issue by bootandy** [jenkinsci/slack-plugin#113] opened 2015-07-08 14:37 UTC
Plugin: Version 1.7. Jenkins 1.554.3. Chrome browser

Checking "Notify Repeated Failure" results in the tick in checkbox moving to "Include Test Summary" when the config is saved. 
Interestingly selecting both checkboxes leaves them both checked.

**Comment by samrocketman** [comment] 2015-07-08 18:24
This bug has already been fixed in the 1.8 release.  Please upgrade to the latest version.  Duplicate of #66.

**Closed** 2015-07-09 03:22 UTC
Labels: duplicate
