### ISSUE TITLE
Allow slack to post through a proxy

### ISSUE THREAD

**Issue by trevcor** [jenkinsci/slack-plugin#148] opened 2015-11-10 14:25 UTC
Would be a great feature to allow slack to post through a proxy for cases where Jenkins is running behind a firewall.

**Comment by samrocketman** [comment] 2015-11-10 21:05
I don't actively develop this plugin.  I maintain pull requests and releases.  Contributions providing this functionality are welcome!

**Comment by nevermindr** [comment] 2015-11-19 17:19
@trevcor you mean HTTP/HTTPS proxy?
There is already a similar issue https://github.com/jenkinsci/slack-plugin/issues/102

**Comment by okram999** [comment] 2016-05-27 16:33
won't this proxy setting on the jenkins help here? Don't have an env to test. https://wiki.jenkins-ci.org/display/JENKINS/JenkinsBehindProxy

**Comment by tonka3000** [comment] 2016-05-27 17:06
@okram999 this does not work with the actual version, but the git plugin use it, so it should be possible to use the information.

**Comment by facastagnini** [comment] 2016-10-12 17:19
Guys have you seen #171  and #253 ?

**Comment by nevermindr** [comment] 2017-03-21 21:31
I think this also should have been resolved in #156 #299 
Will test in my enterprise environment

**Comment by caleyg** [comment] 2017-10-19 21:55
Can anyone please give me some insight here. I'm trying to use this plugin in my Jenkins Pipeline build.

slackSend isn't honoring http_proxy, https_proxy, or HTTP_PROXY, HTTPS_PROXY or -Dhttp.proxyHost or -Dhttps.proxyHost.

I know Jenkins use the proxy by leveraging one of the environment variables above, because I'm able to do things like install plugins from the plugin manager, and use the proxy in various other build tasks.

But consistently the slack plugin just times out when connecting to slack.com

I'm very close to pivoting and leveraging curl to send my requests...

**Comment by kedziorm** [comment] 2018-02-20 13:45
Could you be so kind and tell me what is the status?

I can confirm that setting proxy according to [https://wiki.jenkins.io/display/JENKINS/JenkinsBehindProxy](https://wiki.jenkins.io/display/JENKINS/JenkinsBehindProxy) seems to not work for the Slack Notification plugin.

**Comment by timja** [comment] 2018-11-28 15:05
PRs welcome...

**Comment by Eriten** [comment] 2019-03-12 01:01
@timja Since Slack doesn't respect the proxy set through JVM arguments, would it make sense to use the suggested solution in https://github.com/jenkinsci/slack-plugin/pull/171. It's not the cleanest solution but it "can" work. When time is available, I'd want to look into the codebase to see if there's a more elegant solution. It sounds to me that it was able to use `-Dhttp.proxyHost`, but until some point, it stopped working...

**Comment by Eriten** [comment] 2019-03-12 03:44
I've made some progress in investigating this issue. The proxy is not respected because `ProxyConfiguration` needs to be set in Jenkins. This is not set through passing JVM `http.proxyX` arguments (https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L215). Follow  https://github.com/geerlingguy/ansible-role-jenkins/issues/28 to set up `ProxyConfiguration` at startup and your Slack plugin should respect the proxy before hitting your Slack URL.

**Comment by timja** [comment] 2019-03-12 08:17
`ProxyConfiguration` is the way jenkins does it,

So that works?

**Comment by Eriten** [comment] 2019-03-13 17:41
Yes, that worked. For testing I've ran the following from https://github.com/geerlingguy/ansible-role-jenkins/issues/28 in script console. Moving forward, I plan to put it in `init.groovy.d` so that this will be set up at startup.

```
import jenkins.model.*

def instance = Jenkins.getInstance()

final String name = "{{ jenkins_proxy_host }}"
final int port = {{ jenkins_proxy_port }}
final String userName = "{{ jenkins_proxy_user }}"
final String password = "{{ jenkins_proxy_pass }}"
final String noProxyHost = "{{ jenkins_proxy_exceptions }}"

final def pc = new hudson.ProxyConfiguration(name, port, userName, password, noProxyHost)
instance.proxy = pc
instance.save()
println "Proxy settings updated!"
```

**Comment by timja** [comment] 2019-03-13 17:54
Ok you can also do it in the configuration as code plugin,
This PR will be merged shortly and then it would look like:

```
jenkins:
  proxy:
    name: "proxyhost"
    port: 80
    userName: "login"
    password: "password"
    noProxyHost: "externalhost"
    testUrl: "http://google.com"
```

**Closed** 2019-03-13 17:55 UTC
Labels: contributions welcome

**Comment by devantoine** [comment] 2019-03-19 14:11
@timja Thing is: if the proxy is not set up you cannot install any plugin so you won't be able to use JCasC.

**Comment by timja** [comment] 2019-03-19 14:21
JCasC doesn't manage plugin installation,
not sure the relevancy of your comment,

Plugins should be installed before jenkins starts up

**Comment by casz** [comment] 2019-03-19 14:34
@devantoine in JCasC version 1.8 we just removed plugin installation support that marked beta feature.
