### ISSUE TITLE
Don't store global config per job

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#159] opened 2015-11-22 18:35 UTC
I feel a major source of issues this plugin faces is how it stores global config in every job.  What it should do instead is reference the global config in the Jenkins runtime.  Job config should only contain settings related to the job.

This has caused issues in the past like updating global config not properly propagating to all jobs.  As we move to slack-2.0 and beyond I could see this causing problems even more.  As issues are opened related to this I'll link them to this issue.

If anybody feels like tackling this issue I welcome contributions!

**Comment by nevermindr** [comment] 2015-11-22 21:05
You mean things like teamDomain, token and channels?

I've tested this with `2.0-SNAPSHOT` by creating new jobs - in both cases teamDoman, token, room parameters were not set:

```
      <teamDomain></teamDomain>
      <token></token>
      <room></room>
      <startNotification>false</startNotification>
      <notifySuccess>false</notifySuccess>
      <notifyAborted>false</notifyAborted>
      <notifyNotBuilt>false</notifyNotBuilt>
      <notifyUnstable>false</notifyUnstable>
      <notifyFailure>false</notifyFailure>
      <notifyBackToNormal>false</notifyBackToNormal>
      <notifyRepeatedFailure>false</notifyRepeatedFailure>
      <includeTestSummary>false</includeTestSummary>
      <showCommitList>false</showCommitList>
      <includeCustomMessage>false</includeCustomMessage>
      <customMessage></customMessage>
```

So this does not seem to be an issue in `2.0-SNAPSHOT. 
We could handle this during settings migration by nullifying job configuration parameters, if they are equal with the ones from global config. Will this have undesired side-effects?

**Comment by samrocketman** [comment] 2015-11-23 00:56
I haven't really looked at how 2.0 stores the config.  I know 1.8 has this problem.  And because the settings in the 2.0 version are stored in the same xml namespace I foresee potential problems I think.  I could be wrong.  It's been a while since I've looked into it.

**Comment by SuperTux88** [comment] 2015-12-10 16:13
This is a duplicate of #130.

**Comment by samrocketman** [comment] 2015-12-12 08:30
Good call.

**Closed** 2015-12-12 08:31 UTC
Labels: duplicate
