### ISSUE TITLE
Workflow plugin integration

### ISSUE THREAD

**Issue by thisismana** [jenkinsci/slack-plugin#50] opened 2015-02-23 13:16 UTC
The plugin should implement `SimpleBuildStep` to allow being called from the workflow-plugin https://github.com/jenkinsci/workflow-plugin

**Comment by samrocketman** [comment] 2015-02-23 23:04
I do not actively develop this plugin. I will maintain pull requests and releases from now on. Please feel free to contribute this feature!

**Comment by samrocketman** [comment] 2015-02-25 00:36
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by Jeff-Symphony** [comment] 2015-02-25 03:34
I started working on this: https://github.com/Jeff-Symphony/slack-plugin/commit/48238222c8091ad7f5fce3e76098c3ea67f9a070
The integration itself works, but I'm having trouble getting Jenkins' global Slack settings, which means the user would have to set them specifically when adding the workflow step.

I'm open to help on this.

**Comment by thebignet** [comment] 2015-11-04 13:27
Any luck getting this to work ?

**Comment by kmadel** [comment] 2016-03-14 16:28
See merged PR #167

**Comment by OwensCode** [comment] 2016-03-16 16:06
I'm having trouble getting 2.0 to work because of a ```Dependency workflow-step-api (1.11) doesn't exist``` error when installing the plugin on a clean install. Not sure if anyone else has reported it. Getting it while trying to troubleshoot #188. Looks like the workflow plugin was maybe replaced by pipeline?

**Comment by OwensCode** [comment] 2016-03-16 16:18
Seems to be working correctly with the downloaded 2.0 release, but not if I build it locally. Odd. Please let me know if you know why.

**Comment by kmadel** [comment] 2016-04-23 11:59
@OwensCode What are the specific errors you are getting when you build locally?

The workflow(now pipeline, but the package names didn't change) dependencies start here:
https://github.com/jenkinsci/slack-plugin/blob/master/pom.xml#L113

**Comment by OwensCode** [comment] 2016-04-25 15:07
@kmadel When I build the Slack plugin locally and try to install it by uploading the .hpi file through the Advanced tab in the Plugin Manager in Jenkins I get this error:

> SEVERE: Failed to install slack
java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1383)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to install slack plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:508)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1379)
	... 5 more
Caused by: java.io.IOException: Dependency workflow-step-api (1.11) doesn't exist
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:498)
	... 6 more

This is on docker using jenkinsci/jenkins-1.652. If I manually install the workflow/pipeline plugins beforehand, then it works fine. I wonder if Jenkins does not automatically download and install dependencies when you install the plugin from a local file uploaded.

Let me know if I can provide any more info.

**Comment by ssbarnea** [comment] 2016-05-28 16:30
I build and installed the plugin on latest Jenkins 2.6 and it worked. In my case those dependency plugins were already installed.

**Comment by s0undt3ch** [comment] 2016-05-28 17:27
I had no issues after installing the plugin however the pipeline snippet generator doesn't produce anything good to work with...

**Comment by NitroPye** [comment] 2016-06-06 19:53
Has anyone gotten the plugin to work in a post-build way via a pipeline script?

Sending a slack message from the Jenkinsfile is nice but I'm trying to get it to fire off notifications as post-build actions.

https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#code-step-code-general-build-step

**Comment by paralin** [comment] 2016-09-30 17:19
@NitroPye did you ever figure this out? I'd like the same.

**Comment by NitroPye** [comment] 2016-09-30 17:34
@paralin I ended up wrapping everything in a massive try/catch and then rolled that into a groovy function for other Jenkinsfiles to use. It looks something like this (this ons is called `standardDockerBuild`:

```
def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  node('docker') {
    try {
      // build steps go here
    } catch(e) {
      currentBuild.result = 'FAILURE'
      throw e
    } finally {  
      stage('Post Build') {
        if (config.slackChannel) {
          def color = 'good'
          def message = 'Build Succeeded'
          if (currentBuild.result == 'FAILURE') {
            color = 'danger'
            message = 'Build Failed'
          }
          slackSend channel: config.slackChannel, color: color, message: message + " - ${cleanJobName} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }
      }
    }
  }
}
```
Then we use this function like this:
```
standardDockerBuild {
  slackChannel = '#notifications'
}
```

I know this is probably a bit more than you asked for but you could in theory use the try/catch/finally method in a standard Jenkinsfile. I found it so clunky that I moved it all out into a central place so our team doesn't have to re-implement this logic 125 times.

**Comment by paralin** [comment] 2016-09-30 17:35
@NitroPye Neat. Thanks so much for sharing. You put the function into a common Pipeline script that every pipeline can access in your Jenkins config right?

**Comment by NitroPye** [comment] 2016-09-30 17:36
@paralin Yep thats exactly what we did. Its a bit more complex as we have options for buildScript lintingScript, etc but so far its working great across our team.

**Comment by paralin** [comment] 2016-09-30 17:46
@NitroPye Would it be possible to make what you've done a wrapper, so:

```
standardDockerBuild ("#notifications") {
  # Custom build steps here
}
```

**Comment by NitroPye** [comment] 2016-09-30 17:50
@paralin that seems like it could work. I'm super unfamiliar with Groovyscript. What we ended up doing for the buildScripts is actually more like this

```
standardDockerBuild {
  slackChannel = '#notifications'
  buildScript = '''
cd /usr/src/app
npm run build
'''
```

And inside the common pipeline:

```
sh config.buildScript
```

I like the idea of a wrapper you are proposing better, not sure how to do it though. It could be super simple but I've written like 4 lines of Groovy and or Java my entire career 😂

**Comment by timja** [comment] 2018-11-28 11:54
can't see an issue here? looks resolved ages ago

**Closed by timja** 2018-11-28 11:54 UTC
Labels: contributions welcome
