### ISSUE TITLE
Notify for repeated failures doesn't work

### ISSUE THREAD

**Issue by cheries** [jenkinsci/slack-plugin#136] opened 2015-10-01 00:59 UTC
Slack plugin version 1.8
Jenkins version 1.611

All other options (notify on start/fail/success/etc) work fine, but notify for repeated failure does not produce any notifications.  Also, nothing comes up in the jenkins logs.

**Comment by samrocketman** [comment] 2015-10-01 03:49
Could not reproduce.  Versions tested:

* Jenkins: 1.631 (currently latest as of today), Slack: 1.8
* Jenkins: 1.611, Slack: 1.8

Steps taken to attempt to reproduce.

* Leave "notify for repeated failure" unchecked
* Failed build 3 times
* Enable "notify for repeated failure"
* Failed build 3 times

Expected behavior was witnessed.

* When "notify for repeated failure" was unchecked and the build failed 3 times; I only saw a single notification for the first build but the second two builds did not notify.
* When "notify for repeated failure" was enabled and the build failed 3 times; All three builds notified slack.

I couldn't reproduce the behavior you reported.  Perhaps you have your job improperly configured somehow.  Did you upgrade the plugin and witnessed the poor behavior?  If so, go into your jobs and save the job configuration again to overwrite any potential bad settings.  The upgrade process of this plugin is currently shoddy.

If you would like to witness the proper behavior yourself then feel free to [bootstrap jenkins with slack configured](https://github.com/samrocketman/jenkins-bootstrap-slack) and join [jenkins-slack-plugin.slack.com](https://jenkins-slack-plugin.slack.com) (see [self sign up](https://jenkins-slack-testing-signup.herokuapp.com/)).

To test the older version Jenkins 6.311:

* update [the version of this line](https://github.com/samrocketman/jenkins-bootstrap-slack/blob/master/build.gradle#L33) for the version you wish to test (6.311)
* execute `./slack_bootstrap.sh` to spin up Jenkins with slack configured.
* Run the `Test` job as a build and be sure to check the `fail` box when building.

**Comment by cheries** [comment] 2015-10-01 06:07
Hi Sam, thank you for the quick and detailed reply.  I bootstrapped jenkins with slack, but the same behavior occurs.  
Steps to reproduce (should have included in my OP):
1. In job slack config, check only "Notify Repeated Failure"
2. Failed build 3 times

Observed: No slack notifications
Expected: Slack notifications on 2nd & 3rd failures

Only when I added a check for "Notify Failure" on the 4th run did it start sending notifications.
My use case here is to not send a notification on a first failure, but to only notify for any repeated failures.  I'm starting to guess that maybe this wasn't the intention for the feature.

**Comment by samrocketman** [comment] 2015-10-01 15:01
I understand the desired behavior.  I don't think that was the original intention but you could always submit a patch.  Contributions are welcome to make it behave this way.  It shouldn't affect existing behavior as I originally described.  I don't actively develop this plugin.  I only maintain pull requests and releases.

**Comment by samrocketman** [comment] 2015-10-10 06:50
I don't mind working on a fix for this tomorrow.  I'll open a pull request for review.

**Closed** 2015-10-27 06:00 UTC
Labels: contributions welcome
